name: application_management
version: 0.0.1
description: Supports the operation of native applications in the form of plugins.
homepage: https://github.com/Nomeleel/application_management
repository: https://github.com/Nomeleel/application_management
issue_tracker: https://github.com/Nomeleel/application_management/issues

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.applicationManagement.plugin
        pluginClass: ApplicationManagementPlugin
      ios:
        pluginClass: ApplicationManagementPlugin
